### ISSUE TITLE
[ERROR] 13:00:00 Error: ENOENT: no such file or directory, open 'C:\Users\Nilton Filho do Rei\Desktop\Rocketseat\NLW\NLW-03-Rodrigo_Novais\server\src\keys\private.key'

### ISSUE THREAD

**Issue by georgearmando** [RodrigoNovais/rocketseat-nlw-3#1]
Segui os passos descritos no README, e surgiu este erro quando corre o comando
npm run start 

![image](https://user-images.githubusercontent.com/31625125/97299683-a4235d80-1855-11eb-82ed-25a02ce66d07.png)

**Comment by RodrigoNovais** [comment]
Para fins de encriptação, é necessário prover um par de chaves RSA
Dentro da pasta `src`, crie um diretório `keys` e armazene as chaves RSA com os nomes:

- `private.key` para a chave privada e
- `public.key` para a chave publica

Desde 2015, é recomentado uma `Key Size` de pelo menos 2048-bits

Desculpe a demora para visualizar a issue
Irei atualizar o README de imediato
